apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sempervigil.componentFullname" (list . "web-nginx") }}
  labels:
    {{- include "sempervigil.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       8080;
        server_name  _;
        absolute_redirect off;
        port_in_redirect off;
    
        root /usr/share/nginx/html/current;
        index index.html;

        location ^~ /feed/ {
            root /usr/share/nginx/html;
            try_files /shared$uri /current$uri =404;
        }
    
        location / {
            try_files $uri $uri/ =404;
        }
    }
