apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sempervigil.componentFullname" (list . "web-nginx") }}
  labels:
    {{- include "sempervigil.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       8080;
        server_name  _;
        absolute_redirect off;
        port_in_redirect off;
    
        root /usr/share/nginx/html/current;
        index index.html;
    
        location ^~ /vendor/ {
            rewrite ^/vendor/([^/]+)/?$ /entities/?search=$1 permanent;
        }
    
        location ^~ /product/ {
            rewrite ^/product/([^/]+)/?$ /entities/?search=$1 permanent;
        }
    
        location ^~ /threat/ {
            rewrite ^/threat/([^/]+)/?$ /entities/?search=$1 permanent;
        }
    
        location = /vendor/ { return 301 /entities/; }
        location = /product/ { return 301 /entities/; }
        location = /threat/ { return 301 /entities/; }
        location = /vendors/ { return 301 /entities/; }
        location = /products/ { return 301 /entities/; }
        location = /threats/ { return 301 /entities/; }
    
        location / {
            try_files $uri $uri/ =404;
        }
    }
