apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sempervigil.secretName" . }}
  labels:
    {{- include "sempervigil.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.externalDatabase.existingSecret) (not .Values.postgresql.enabled) .Values.externalDatabase.host }}
  url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.externalDatabase.username .Values.externalDatabase.password .Values.externalDatabase.host .Values.externalDatabase.port .Values.externalDatabase.database | quote }}
  password: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
  SV_ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  SEMPERVIGIL_MASTER_KEY: {{ .Values.secrets.sempervigilMasterKey | quote }}
  SEMPERVIGIL_KEY_ID: {{ .Values.secrets.sempervigilKeyId | quote }}
  LITELLM_MASTER_KEY: {{ .Values.secrets.litellmMasterKey | quote }}
  SV_LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  NVD_API_KEY: {{ .Values.secrets.nvdApiKey | quote }}
  PIA_USER: {{ .Values.secrets.piaUser | quote }}
  PIA_PASS: {{ .Values.secrets.piaPass | quote }}
